var found = true;
var grade = 80;
var firstName = "Julia";
var middleName = "Botelho";
found = 0;
grade = "A";
firstName = false;
console.log(found);
console.log("A nota é: " + grade);
//console.log("Meu nome é: " + firstName + " " + middleName);
console.log("Meu nome \u00E9 " + firstName + " " + middleName);
